version: '3.8'

services:
  nginx:
    build: .
    container_name: myngin
    ports:
      - "8080:8080"
    volumes:
      - ./html:/var/www/html
      - ./nginxConf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
